# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
    
    - name: Create .env file
      run: |
        echo "DB_URL=${{ secrets.DATASOURCE_PASSWORD }}" >> ./src/main/resources/.env
        echo "DB_USER=${{ secrets.DATASOURCE_URL }}" >> ./src/main/resources/.env
        echo "DB_PASSWORD=${{ secrets.DATASOURCE_USERNAME }}" >> ./src/main/resources/.env

    - name: Grant execute permission for Gradlew
      run: chmod +x gradlew

    - name: Cache
      uses: actions/cache@v4.1.2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build with Gradle Wrapper
      run: ./gradlew clean build --no-daemon
      env:
        DATASOURCE_PASSWORD: postgres
        DATASOURCE_URL: jdbc:postgresql://localhost:5432/postgres?user=postgres&password=postgres
        DATASOURCE_USERNAME: postgres

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
